version: '3.5'

services:
  backend:
    build: 
      context: https://github.com/docker-hy/ml-kurkkumopo-backend.git
      dockerfile: Dockerfile
    image: backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
  frontend:
    build: 
      context: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
      dockerfile: Dockerfile
    image: frontend
    ports: 
      - 3000:3000
  training:
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-training.git
      dockerfile: Dockerfile
    volumes:
      - imgs:/src/imgs
      - model:/src/model
volumes:
  model:
  imgs:
